- documentation/basics/installation.md
- documentation/tracking/tracking.md
That way, people coming from the tracking docs to the CPLEX installation instructions don't end up reading the ilastik installation instructions.
> Improve link to CPLEX setup using named anchor

- _includes/navbar.html
The link always appeared "active". If highlighting is desired it should be achieved by an appropriate style in css.
> changed jobs menu entry style

- download.html
Fix was needed in description only, the link was correct.
> Fix version number of MacOS binary downloads description to 1.2.2

- documentation/basics/installation.md
Reworked the whole installation page and added instructions for GUROBI installation on Linux and Mac
Fixes #31
> Enh add gurobi instructions

- documentation/basics/headless.md
Instructions for object classification were outdated.
* removed all references to the special command-line flags like
`--export_object_probability_img`
* added instructions for usage of `--export_source`
fixes #36
> Modified instructions for headless mode; --export_source

- documentation/basics/headless.md
See https://github.com/ilastik/ilastik/issues/1422
See https://github.com/ilastik/ilastik/pull/1815
Summary: Due to a bug in python we should discourage using spaces in command line arguments at all
> updated docs on headless mode

- community.html
Ilastik is an official partner of the Image.sc forum, so let's recommend the forum as the primary place to ask questions.
> Add link to new image.sc forum

- documentation/basics/export.md
- documentation/basics/headless.md
This PR reworks a lot of the Headless Operation documentation. Important sections are moved up, less important sections are moved down, and a new "General" section was created, with, well, general advice relevant for every workflow.
There is more info on how to use the arguments and what they mean. Also fixed the instructions on how to use the `--cutout_subregion` argument.
More links.
There are separate sections for each workflow, though we could definitely use more information on them, as well as add the missing ones (say... tracking, maybe?)
Also adds a "Known Issues" section which we might use to document issues that aren't fixed yet, or that are fixed but whose fixes haven't been released yet, or old issues that were fixed in new versions of ilastik. The main intention is to have …
> Headless docs improvements

- documentation/basics/headless.md
Made aware by a forum post that the docs for the headless multicut are missing...
see: https://forum.image.sc/t/running-ilastik-multicut-classifier-from-fiji/24639/2?u=k-dominik
> added docs for multicut headless mode

- assets/ilastik.css
Collapse the navbar on wider screens to avoid wrapping it's contents to the second row.
See https://stackoverflow.com/a/20249415.
Close #99.
> Fix navbar wrapping on certain screen sizes

- documentation/basics/headless.md
- Add ReadOnly=1 option
- Add Link to the python client example included in ilastik.
> Some more documentation on the headless mode.

- documentation/tracking/tracking.md
was made aware by [this post on the forum](https://forum.image.sc/t/ilastiks-automatic-tracking-workflow-cant-extract-object-positions-over-time/38782/3?u=k-dominik) that we don't even mention the other table columns that are exported in tracking.
> Added minor detail about csv-export

- documentation/nn/nn.md
Hi, I think it's better to link to the dedicated link for ilastik in bioimage.io: https://bioimage.io/#/?partner=ilastik , this will bring the user directly to ilastik models.
> Use BioImage.IO community partner link for ilastik

- documentation/basics/headless.md
This change adds a section of interest for Ilastik's headless mode documentation.
See discussions on image.sc forum:
- https://forum.image.sc/t/notable-memory-usage-difference-when-running-ilastik-in-headless-mode-on-different-machines/41144/2
> Add section about hdf5 in the headless mode doc.

- documentation/animalTracking/animalTracking.md
- documentation/tracking/tracking.md
Markdown tables are generated without any classes, but Bootstrap
requires adding `.table` classes in order for a table to be styled.
Closes https://github.com/ilastik/ilastik.github.io/issues/151
> Add Bootstrap classes to Markdown tables

- development.html
updated our development page to reflect, that lazyflow was merged into main ilastik and also added a section to point at our CONTRIBUTING guidelines in ilastik for dev setup.
fixes #204
> bring our dev landing page up to date

- assets/ilastik.css
fixes width for mobile devices
before:
> Add style for youtube iframes

- documentation/basics/headless.md
Object Identities was sadly missing, albeit being maybe the most useful output (with the table)...
Also restructured inputs into a list because I find that easier to find.
> Add Object Identities to avalable export sources

- documentation/basics/export.md
Not sure if we need this note at all, but here's a suggestion for what we could tell people about the OME-Zarr export
> Export docs: Add OME-Zarr note

- download.html
Moved 1.4.1 into the prime position, 1.4.0 to previous stable versions.
**files not yet available**
> Release Candidate announcement 1.4.1rc2

- about.html
> Fix overflow of citation in about page

- documentation/basics/dataselection.md
While going through the documentation, I noticed that the HDF5 link was broken
Since HDF5 is one of the main format used by ilastik, thought we should fix it
This PR fixes the issue by updating the link to one that I feel is the most appropriate (Please lmk if there is a better link)
Earlier it was showing
> Fix broken HDF5 link in documentation

- documentation/basics/installation.md
- documentation/basics/installation_legacy_cplex.md
- documentation/tda/tda.md
- download.html
> Prep 1.4.1
