- documentation/basics/dataselection.md
Updated documentation for v1.2.1, added paragraph about loading stacks
> Short description for stack loading

- index.html
Heyo, added a badge to our twitter account. Looks like this on the site:
> added follow us on twitter badge

- download.html
- index.html
just updated the download links
> updated download links

- download.html
* added 1.3.2 as current release
* moved 1.3.0, 1.2.2 to previous stable releases
> updated release notes

- documentation/basics/batch.md
> Corrected link to h5py docs

- documentation/basics/layers.md
- documentation/index.md
> fixed erroneous links in docs

- _layouts/documentation.html
- assets/ilastik.css
- javascripts/jquery.toc.js
> Add human-readable and copyabple achor links in docs

- download.html
just to point people to the right portion of the page
> added ids in order to link directly to categories in downloads

- documentation/basics/headless.md
- documentation/basics/installation.md
* moved this part from headless to installation as applies to both gui and
headless mode.
* added mention of config file, config file example
> updated description on how to limit resources

- documentation/basics/headless.md
closes https://github.com/ilastik/ilastik/issues/1519
> Added docs for tracking headless mode

- download.html
Reverts ilastik/ilastik.github.io#109
> Revert "update links for 1.3.3post1"

- documentation/basics/installation.md
Include a link to the Apple knowledge base on how to open unsigned macOS apps.
Closes https://github.com/ilastik/ilastik.github.io/issues/112
> Update installation docs for macOS

- documentation/counting/counting.md
it's currently not tested/supported to use cplex in counting.
We might want to re-add this content - hence the commenting out and not deleting, depending on how we proceed with counting
> Removed reference to any usage of cplex

- download.html
1.4.0b4 had a flaw - updated links for 1.4.0b5 :)
> added links for 1.4.0b5

- documentation/objects/objects.md
related to ilastik/ilastik/issues/2251.  Reformatting and code examples for HDF5 files.
> formatting and python code examples for HDF5 files.

- _includes/navbar.html
- _layouts/default.html
Use https://docsearch.algolia.com/ for the search service.
Closes https://github.com/ilastik/ilastik.github.io/issues/164.
> Add doc search

- documentation/basics/headless.md
xref: https://forum.image.sc/t/ilastik-headless-mode-tracking-documentation-question/57280?u=k-dominik
> fix headless cmd flags for tracking

- download.html
updated the download link to a version that works on big sur (updates) and Monterey
> update osx download link

- download.html
> update download links 1.4.0b21

- download.html
- news/_posts/2023-02-20-ilastik-1.4.0.md
> updated links for 1.4.0

- documentation/basics/export.md
Only a few tiny updates, making sure what is in the text there corresponds to current ui
* remove outdated info for image on disk (removed)
* some tiny aesthetic improvements
* `uint8` no longer in the list of formats -> `integer 8-bit`
> Export updates

- index.html
- news/_posts/2023-05-11-trainable-domain-adaptation.md
- news/_posts/2023-07-06-silicon-builds.md
* changed the news widget on the main page to show 3 articles at a time
* added news articles highlighting
* beta of Trainable Domain Adaptation
* native builds for apple silicon
> add more news articles

- download.html
also added note for OSX users, recommending the beta version.
> updated links for ilastik 1.4.0.post1

- documentation/basics/dataselection.md
will also add this information to the stack import dialog.
> Add note on implicit data copy on stack import

- _data/objectfeatures.json
ref: https://github.com/ilastik/ilastik/pull/2847
> updated oc docs with bad feature warning

- download.html
> Update links for ilastik 1.4.1b18

- download.html
> Update links, etc. for ilastik 1.4.1b20

- documentation/objects/objects.md
An attempt to clarify passages of object classification docs that popped up as confusing during the CMCB course
> Object classification docs: Feedback from CMCB course

- documentation/basics/installation.md
* newer versions
* always download the script on mac and linux as we are not shipping it anymore
> updated installation instructions

- documentation/basics/headless.md
> Add instructions for using OME-Zarr headless

- download.html
Will get in touch with iwr people to shut the server down - don't think it adds value in that state.
> Remove links to old server that does not seem functional
